Ejercicio Persona
EmanuelCl/CFL2021 pull request #4
Opened 2021-07-14 00:34 UTC by EmanuelCl

Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
Como puedo poner el lector de archivos en otra clase?

2021-07-14 13:36 UTC, francisco-corti approved these changes

2021-07-14 13:43 UTC, rbeltracchi approved these changes
Falta generalizar el lector de Archivos asi lo podes usar en todos los ejercicios, pero de todas formas estan muy bien

2021-07-14 13:43 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +    private personas: Persona[]
Si queres usar este lector de archivos como una clase generica (es decir que sirva para cualquier ejercicio) tendrias que sacar toda la informacion de personas que tenes aca, ya que si lo comparas con el RegistroPersonas es exactmente igual. El lector lo unico que tendria que hacer es cargar un archivo de una ruta que le pasen por parametro y usar el separador que tambien reciba, asi devuelve un arreglo de strings (cada linea del archivo).

Despues, tendrias que incluir esta clase lector en el registro personas. donde voy a hacer mi siguiente comentario

2021-07-14 13:43 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/RegistroPersonas.ts
> +    private personas: Persona[];
Aca tendrias que agregar una propiedad que sea Lector de archivos e inicializarla en el contrustor

2021-07-14 13:43 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/menuDeOpciones.ts
> +lector.mostrarPersonas();
aca en vez de llamar al lector, el registroPersonas seria el encargado de hacer la carga, llamando internamente al lector de archivos

2021-07-14 13:43 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +    }
Estos dos metodos, tendrian que estar en RegistroPersonas, ya que es esa clase quien se encarga de manejar los tipos exactos de la persona, el lector no tendria que saber lo que esta cargando. entonces en la linea que haces el FS.readFile llamarias al lector para que haga la carga, algo como `lectorArchivos.cargarDatos('personas.txt', '\n')` que son los parametros que espera el lector.

El lector solo ejecutaria esa linea y te devolveria el arreglo de strings, el foreach se tendria que encargar de hacerlo el RegistroPersonas, que es quien sabe que clase de objetos tiene

2021-07-14 22:37 UTC, mauri52 commented on Programacion Orientada a Objetos/Clase 25/Biblioteca/RegistroLibros.ts
> +        let año: number = RLS.questionInt('Ingrese el año: ');
estas lineas se repiten textualmente en el metodo updateLibro, podes hacer algo para evitarlo?

2021-07-15 01:26 UTC, EmanuelCl commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +    }
public cargarPersonas():void{
        let personas:string[] = (FS.readFileSync(this.lectorArchivos.cargaDatos('personas.txt','\n')));
        let propiedadesPersona:string[] = [];
        personas.forEach(personaString => {
            propiedadesPersona = personaString.split(";")
            this.personas.push(new Persona(propiedadesPersona[0],propiedadesPersona[1],propiedadesPersona[2],parseInt(propiedadesPersona[3]),parseInt(propiedadesPersona[4])))
        });
    }

---------------------------------------------------------------

export default class Lector{
    private lectorArchivos:string

    public constructor(lectorArchivos:string){
        this.lectorArchivos = lectorArchivos;

    }
   public cargaDatos(lectorArchivos,separador):string{
       return this.lectorArchivos
   }
}
hola, me esta tirando este error en let personas (Type 'Buffer' is missing the following properties from type 'string[]': pop, push, concat, shift, and 5 more.ts(2740))

2021-07-15 12:55 UTC, francisco-corti commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +    }
Hola Ema, lo que traigas del archivo de texto no va a ser un array hasta que le apliques un **.split()** 
La variable **personas** está declarada como arreglo de strings, pero se esta intentando asignarle algo que en ese momento no es un arreglo.

Por otro lado, el encargado de usar el **fs** para leer, debería ser la clase lector en el metodo **cargarDatos**.
Acordate tambien que al metodo **readFileSync** de fs, le pasamos 2 parametros. **La ruta del archivo** a leer y **el encoding (utf8)**

**En clase Lector:**
```
public cargarDatos(rutaTxt: string, separador: string): void {
   this.datos = fs.readFileSync(rutaTxt, "utf8").split(separador);
}
```

**En clase Persona:**
```
public cargarPersonas(rutaTxt: string,separador: string): void {
   let personas: string[] = this.lectorArchivos.cargarDatos(rutaTxt,separador);
...
```

2021-07-15 15:36 UTC, rbeltracchi requested changes

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +import Persona from "./Persona";
aca no necesitas este import

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +       return this.lectorArchivos
en esta linea no tenes que devolver lectorArchivos, sino hacer el read del archivo con los parametros que te pasaron y devolver ese string

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +    private lectorArchivos:string
esta variable no es necesaria

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/LectorArchivos.ts
> +        this.lectorArchivos = lectorArchivos;
este constructor puede ser vacio

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/RegistroPersonas.ts
> +        this.lectorArchivos=lectorArchivos
aca en vez de recibir el lector por parametro podrias hacerle el new directamente. Asi solo el Registro sabe que lo usa y nadie de afuera le tiene que decir

2021-07-15 15:36 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/RegistroPersonas.ts
> +        let personas:string[] = (FS.readFileSync(this.lectorArchivos.cargaDatos('personas.txt','\n')));
fijate que aca no tiene sentido usar un lector porque el que lee sigue siendo este objeto. Lo que tenes que hacer es que el FS.readFileSync se haga dentro del metodo cargaDatos del lector. y que ese mismo metodo devuelva un array de strings. entonces aca vos directamente decis this.lectorArchivos.cargaDatos(... , ...) y te olvidas de como se lee un archivo

2021-07-15 22:54 UTC, EmanuelCl commented
Arreglado gracias ahí lo volví a subir

2021-07-16 13:44 UTC, rbeltracchi approved these changes

2021-07-16 13:44 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Biblioteca/RegistroLibros.ts
> +        let libros:string[] = (FS.readFileSync('libros.txt','utf8')).split('\n');
aca podrias utilizar el lectorArchivos que creaste

2021-07-16 13:44 UTC, rbeltracchi commented on Programacion Orientada a Objetos/Clase 25/Personas/RegistroPersonas.ts
> +        let dni=Read.questionInt("Ingrese el DNI: ");
Mismo comentario que Mauri mas arriba, esto esta repetido en dos metodos, te animas a dejarlo una sola vez?

2021-07-16 13:55 UTC, francisco-corti commented on Programacion Orientada a Objetos/Clase 25/Personas/RegistroPersonas.ts
> +        let personas:string[] = this.lectorArchivos.cargaDatos("personas.txt",'\ n');
Solo como comentario. Cada vez que instancies un (o varios) registro de personas, vas a estar leyendo desde el mismo archivo. Lo ideal sería que este metodo reciba por parametro la ruta y el separador, para poder instanciar varias clases que lean desde diferentes archivos. Por ej:

```
let registro1 = new RegistroPersonas();
 registro1.cargarPersonas('personas.txt','\n');
 
 let registro2 = new RegistroPersonas();
 registro2.cargarPersonas('otrasPersonas.txt','\n');
```
 
 Otra opcion si solo quisieras permitir que las personas se carguen una unica vez al instanciar la clase, sería que el metodo **cargarPersonas sea privado y se ejecute dentro del constructor**. De esta manera el constructor deberia recibir la ruta del txt y el separador para cargar los datos en el momento de la instanciación. Por ej:
 
 En clase RegistroPersonas:
 
```
 public constructor(rutaArchivo: string, separador: string) {
      this.cargarDatos(rutaArchivo, separador);
} 
```
 
En main:
```
 let registro1 = new RegistroPersonas('personas.txt','\n');
 let registro2 = new RegistroPersonas('otrasPersonas.txt','\n);
```

2021-07-19 16:33 UTC, merged